### ISSUE TITLE
Not working on Safari

### ISSUE THREAD

**Issue by mblinsitu** [nomve/Tuio.js#4]
canvas.html example does not work on Safari (9.0.3 on El Capitan): the canvas stays blank.
(It works fine on Chrome, and the original Tuio.js worked fine on both Safari and Chrome.)

The error message in Web inspector console is:

>  TuioCanvas.bundle.js:20137  The header of an OSC packet didn't contain an OSC address or a #bundle string. Header was: 

The error is repeated for each incoming event.

The same error occurs with the Tuio2Simulator from the TUIO2 reference implementation (modified to replace the TCP server with a websocket server), as well as when using the legacy TUIO-to-websocket node server.

**Comment by nomve** [comment]
Hi,

thanks for the report. It was a bug in osc.js that handles the OSC messages. I've updated it to a newer version where the issue was fixed.
