### ISSUE TITLE
How to require?

### ISSUE THREAD

**Issue by tknobi** [nomve/Tuio.js#7]
I'm using Browserify to bundle my package. What is the best way to require your package?

Actually I did this:

```
const Tuio = require('tuio-extended/src/Tuio');
Tuio.Client = require('tuio-extended/src/TuioClient');
Tuio.Cursor = require('tuio-extended/src/TuioCursor');
Tuio.Object = require('tuio-extended/src/TuioObject');
```

It's working, but seems to be very complicated.

**Comment by nomve** [comment]
yes, that's how I used it too. If I recall correctly, it was too much work to do anything else because of how the library was originally done.
